var toh_debug=false;if(window.location.search){var urlQueryStr=window.location.search;if(urlQueryStr.indexOf("toh_debug")!=-1){var toh_debug=true;}}
var hostname=document.location.hostname.split('.');var loop_limit=0;if(hostname.length>2){loop_limit=1;}
for(i=hostname.length-1;i>=loop_limit;i--){top_level_domain=hostname.slice(i).join('.');}
if(toh_debug){console.log("top_level_domain");console.log(top_level_domain);}
var win_width=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth;var device_type="desk";if(win_width<970&&win_width>727){device_type="tab";}else if(win_width<728){device_type="mob";}
var PREBID_TIMEOUT=1000;var pbjs=pbjs||{};pbjs.que=pbjs.que||[];(function(){var d=document,pbs=d.createElement("script");pbs.async=true;var useSSL='https:'==d.location.protocol;pbs.type="text/javascript";pbs.src="https://www.thisoldhouse.com/ad-wrapper/prebid.js";var target=document.getElementsByTagName("head")[0];target.insertBefore(pbs,target.firstChild);})();var googletag=googletag||{};googletag.cmd=googletag.cmd||[];(function(){var gads=document.createElement('script');gads.async=true;gads.type='text/javascript';var useSSL='https:'==document.location.protocol;gads.src=(useSSL?'https:':'http:')+'//www.googletagservices.com/tag/js/gpt.js';var node=document.getElementsByTagName('script')[0];node.parentNode.insertBefore(gads,node);})();(function(modules){var installedModules={};function __webpack_require__(moduleId){if(installedModules[moduleId])
return installedModules[moduleId].exports;var module=installedModules[moduleId]={exports:{},id:moduleId,loaded:false};modules[moduleId].call(module.exports,module,module.exports,__webpack_require__);module.loaded=true;return module.exports;}
__webpack_require__.m=modules;__webpack_require__.c=installedModules;__webpack_require__.p="";return __webpack_require__(0);})
([function(module,exports,__webpack_require__){var predefinedSlots=__webpack_require__(1),googleHelper=__webpack_require__(2),domainConf=__webpack_require__(5),configuration=__webpack_require__(3);window.tohAdWrapper={slots:[],pushQueues:[],displayQueues:[],override_conf:function(conf){configuration.override(conf);},push:function(adName,adId,opts){var slotInfo=predefinedSlots.getSlot(adName);if(slotInfo===false)
return'';domainConf.overrideConf();googleHelper.dfpInit();if(configuration.get['ad_disable'])return"";if(toh_debug){console.log("calling main push method for "+adId);}
if(domainConf.isReadyDomainConf){this.defineSlot(adName,adId);}else{this.pushQueues[adId]=adName;}},display:function(adId){var curThis=this;if(configuration.get('ad_disable'))return"";if(toh_debug){console.log("calling main display method for "+adId);}
if(domainConf.isReadyDomainConf){googleHelper.cmdDisplay(adId);}else{this.displayQueues[adId]=adId;}},defineSlot:function(adName,adId){var slotInfo=predefinedSlots.getSlot(adName);this.slots[adId]={"ad_name":adName,"slot_name":slotInfo.getName(),"ad_size":{"desk":slotInfo["slot"]["wh"],"tab":slotInfo["slot"]["wh_tab"],"mob":slotInfo["slot"]["wh_mob"]}};var domain=window.location.hostname;googleHelper.cmdPush({adName:adName,adId:adId,domain_name:domain,slotSize:slotInfo.getAttr("wh")});}};},function(module,exports){var slots={'leaderboard':{'wh':[728,90],'wh_tab':[728,90],'wh_mob':[320,50],'size_map':[[[320,50],[320,50]],[[728,90],[728,90]]],'slot_name':'top_leader_board_ad_slot'},'mobile_leaderboard':{'wh':[320,50],'wh_tab':[320,50],'wh_mob':[320,50],'size_map':[[[320,50],[320,50]]],'slot_name':'top_leader_board_ad_slot'},'large_leaderboard':{'wh':[970,90],'wh_tab':[728,90],'wh_mob':[320,50],'size_map':[[[320,50],[320,50]],[[728,90],[728,90]],[[970,90],[970,90]]],'slot_name':'parallax_ad_slot'},'billboard':{'wh':[970,250],'wh_tab':[300,250],'wh_mob':[300,250],'size_map':[[[300,200],[300,250]],[[970,200],[970,250]]],'slot_name':'parallax_ad_slot'},'medium_rectangle':{'wh':[300,250],'wh_tab':[300,250],'wh_mob':[[300,250],[320,50]],'size_map':[[[300,200],[300,250]]],'slot_name':'rightrail_ad_300_250_1_slot'},'half_page':{'wh':[300,600],'wh_tab':[300,600],'wh_mob':[300,600],'size_map':[[[300,400],[300,600]]],'slot_name':'rightrail_ad_300_600_1_slot'},'skyscraper':{'wh':[160,600],'wh_tab':[160,600],'wh_mob':[160,600],'size_map':[[[160,400],[160,600]]],'slot_name':'skyscraper_slot'},'text_link':{'wh':[300,250],'wh_tab':[300,250],'wh_mob':[300,250],'size_map':[[[300,200],[300,250]]],'slot_name':'text_link_slot'}};module.exports={slots:slots,getSlot:function(name){if(this.slots[name]===undefined)
return false;return{slot:this.slots[name],getName:function(){return this.slot['slot_name'];},getAttr:function(attr){return this.slot[attr];}}}};},function(module,exports,__webpack_require__){var configuration=__webpack_require__(3),sha1Helper=__webpack_require__(4),predefinedSlots=__webpack_require__(1);module.exports={disableDfpInitialLoad:false,dfpSlots:[],dfpInit:function(){if(this.disableDfpInitialLoad)return;this.disableDfpInitialLoad=true;googletag.cmd.push(function(){googletag.pubads().disableInitialLoad();});},cmdPush:function(info){var define_slot='',scope=this;googletag.cmd.push(function(){size_mapping=scope.sizeMap(info.adName);slotPath=configuration.getSlotPath();define_slot=googletag.defineSlot(slotPath,info.slotSize,info.adId).defineSizeMapping(size_mapping).setTargeting("AdType",info.adName).setTargeting("Domain",info.domain_name).addService(googletag.pubads());scope.attachSetTargeting(define_slot);scope.addPageKeyValue(define_slot);scope.addPageUrlKeyValue(define_slot);scope.setDfpCategoryExclusion(define_slot);googletag.pubads().enableAsyncRendering();googletag.pubads().collapseEmptyDivs();googletag.enableServices();scope.dfpSlots[info.adId]=define_slot;});},sizeMap:function(adName){var slotInfo=predefinedSlots.getSlot(adName),size_map=slotInfo.getAttr("size_map"),size_mapping="";googletag.cmd.push(function(){size_mapping=googletag.sizeMapping();size_map.forEach(function(value){size_mapping=size_mapping.addSize(value[0],value[1]);});size_mapping=size_mapping.build();});return size_mapping;},cmdDisplay:function(adId){var scope=this;googletag.cmd.push(function(){googletag.display(adId);scope.refreshSlot(adId);})},attachSetTargeting:function(define_slot){var add_key=configuration.get('add_key');for(var key in add_key){var value=add_key[key];define_slot.setTargeting(value[0],value[1]);}},addPageKeyValue:function(define_slot){var page_add_key=configuration.get('page_add_key');for(var key in page_add_key){var value=page_add_key[key];define_slot.setTargeting(value[0],value[1]);}},addPageUrlKeyValue:function(define_slot){var url=window.location.pathname;define_slot.setTargeting("FURL",url);if(url.length>40){var url=sha1Helper.getSha1(url);define_slot.setTargeting("SURL",url);}},setDfpCategoryExclusion:function(define_slot){var exclusion_cat=configuration.get('exclusion_cat');for(var key in exclusion_cat){define_slot.setCategoryExclusion(exclusion_cat[key]);}},refreshSlot:function(adId){slots_info=tohAdWrapper.slots;if(toh_debug){console.log("Calling refresh method for "+adId);}
if(typeof slots_info[adId]=="undefined"||typeof slots_info[adId]["slot_name"]=="undefined"){console.log("TOH DEBUG: Ad calling declaration is wrong for "+ adId);return"";}
var slot_name=slots_info[adId]["slot_name"];if(toh_debug){console.log("configuration values");console.log(configuration.values);console.log("slots_info");console.log(slots_info);}
if(typeof configuration.values.hb_slot_config=="undefined"){this.refreshSlotWithoutPrebid(adId);}else{if(typeof configuration.values.hb_slot_config[slot_name]=="undefined"){this.refreshSlotWithoutPrebid(adId);}else{this.refreshSlotWithPrebid(adId);}}},refreshSlotWithoutPrebid:function(adId){if(toh_debug){console.log("calling refreshSlotWithoutPrebid method");}
var slot=this.dfpSlots[adId];googletag.cmd.push(function(){googletag.pubads().refresh([slot],{changeCorrelator:false});});},refreshSlotWithPrebid:function(adId){if(toh_debug){console.log("calling refreshSlotWithPrebid method");}
var slot=this.dfpSlots[adId];var ad_unit_code=slot.getSlotElementId();var adUnits=this.processAdUnits(adId,ad_unit_code);if(toh_debug){console.log("adUnits processing");console.log(adUnits);}
googletag.cmd.push(function(){pbjs.que.push(function(){pbjs.addAdUnits(adUnits);pbjs.setPriceGranularity("dense");pbjs.requestBids({timeout:PREBID_TIMEOUT,adUnitCodes:[ad_unit_code],bidsBackHandler:function(){if(toh_debug){pbjs.addCallback('adUnitBidsBack',function(bidValue){console.log('======= toh_debug: Bid Value =======');console.log(bidValue);});}
pbjs.setTargetingForGPTAsync([ad_unit_code]);googletag.pubads().refresh([slot],{changeCorrelator:false});}});});});},processAdUnits:function(adId,ad_unit_code){var bid_config=configuration.values.hb_slot_config;var bidIdKey={"appnexus":"placementId","sovrn":"tagid","sonobi":"ad_unit"};var hb_adapter_list=configuration.values.hb_adapter_list,slots_info=tohAdWrapper.slots,slot_name=slots_info[adId]["slot_name"],ad_name=slots_info[adId]["ad_name"],slot_size=slots_info[adId]["ad_size"][device_type],slot_name_key=this.getSlotNameKey(slot_name),bid_array=new Array();for(var k in hb_adapter_list){var v=hb_adapter_list[k];if(typeof bid_config[slot_name_key]==="undefined")return true;if(typeof bid_config[slot_name_key][v]==="undefined")return true;var bid_value=bid_config[slot_name_key][v][device_type];for(var key in bid_value){var value=bid_value[key];var paramKey=bidIdKey[v];var paramObj={};if(typeof value==='object'){var paramValue={};for(var key2 in value){var value2=value[key2];if(key2=="cp"||key2=="ct"){value2=parseInt(value2);}
paramValue[key2]=value2;}
paramObj=paramValue;}else{paramObj[paramKey]=value;}
var bidObj={bidder:v,params:paramObj};bid_array.push(bidObj);}}
var adUnits=[{code:ad_unit_code,sizes:slot_size,bids:bid_array}];return adUnits;},getSlotNameKey:function(slot_name){if(slot_name.indexOf("widget_ad_")!=-1){slot_name_key="widget_ad_global";}else if(slot_name.indexOf("step_ad_")!=-1){slot_name_key="step_ad_global";}else if(slot_name.indexOf("rightrail_ad_300_600_2")!=-1){slot_name_key="rightrail_ad_300_600_2_slot";}else if(slot_name.indexOf("gallery_popup_ad_300_600_slot")!=-1){slot_name_key="gallery_popup_ad_300_600_slot";}else{slot_name_key=slot_name;}
return slot_name_key;}};},function(module,exports){module.exports={values:{'dfp_account':142694468,"add_key":[],"exclusion_cat":[],'hb_slot_config':"",'hb_adapter_list':["appnexus","sovrn","pulsepoint","sonobi"],'page_add_key':[],'ad_disable':false},override:function(conf){Object.assign(this.values,conf);},getSlotPath:function(){return"/142694468/MOV";},get:function(name){return this.values[name];}};},function(module,exports){module.exports={getSha1:function(msg){function rotate_left(n,s){var t4=(n<<s)|(n>>>(32-s));return t4;};function lsb_hex(val){var str="";var i;var vh;var vl;for(i=0;i<=6;i+=2){vh=(val>>>(i*4+4))&0x0f;vl=(val>>>(i*4))&0x0f;str+=vh.toString(16)+ vl.toString(16);}
return str;};function cvt_hex(val){var str="";var i;var v;for(i=7;i>=0;i--){v=(val>>>(i*4))&0x0f;str+=v.toString(16);}
return str;};function Utf8Encode(string){string=string.replace(/\r\n/g,"\n");var utftext="";for(var n=0;n<string.length;n++){var c=string.charCodeAt(n);if(c<128){utftext+=String.fromCharCode(c);}
else if((c>127)&&(c<2048)){utftext+=String.fromCharCode((c>>6)|192);utftext+=String.fromCharCode((c&63)|128);}
else{utftext+=String.fromCharCode((c>>12)|224);utftext+=String.fromCharCode(((c>>6)&63)|128);utftext+=String.fromCharCode((c&63)|128);}}
return utftext;};var blockstart;var i,j;var W=new Array(80);var H0=0x67452301;var H1=0xEFCDAB89;var H2=0x98BADCFE;var H3=0x10325476;var H4=0xC3D2E1F0;var A,B,C,D,E;var temp;msg=Utf8Encode(msg);var msg_len=msg.length;var word_array=new Array();for(i=0;i<msg_len-3;i+=4){j=msg.charCodeAt(i)<<24|msg.charCodeAt(i+1)<<16|msg.charCodeAt(i+2)<<8|msg.charCodeAt(i+3);word_array.push(j);}
switch(msg_len%4){case 0:i=0x080000000;break;case 1:i=msg.charCodeAt(msg_len-1)<<24|0x0800000;break;case 2:i=msg.charCodeAt(msg_len-2)<<24|msg.charCodeAt(msg_len-1)<<16|0x08000;break;case 3:i=msg.charCodeAt(msg_len-3)<<24|msg.charCodeAt(msg_len-2)<<16|msg.charCodeAt(msg_len-1)<<8|0x80;break;}
word_array.push(i);while((word_array.length%16)!=14)word_array.push(0);word_array.push(msg_len>>>29);word_array.push((msg_len<<3)&0x0ffffffff);for(blockstart=0;blockstart<word_array.length;blockstart+=16){for(i=0;i<16;i++)W[i]=word_array[blockstart+i];for(i=16;i<=79;i++)W[i]=rotate_left(W[i-3]^W[i-8]^W[i-14]^W[i-16],1);A=H0;B=H1;C=H2;D=H3;E=H4;for(i=0;i<=19;i++){temp=(rotate_left(A,5)+((B&C)|(~B&D))+ E+ W[i]+ 0x5A827999)&0x0ffffffff;E=D;D=C;C=rotate_left(B,30);B=A;A=temp;}
for(i=20;i<=39;i++){temp=(rotate_left(A,5)+(B^C^D)+ E+ W[i]+ 0x6ED9EBA1)&0x0ffffffff;E=D;D=C;C=rotate_left(B,30);B=A;A=temp;}
for(i=40;i<=59;i++){temp=(rotate_left(A,5)+((B&C)|(B&D)|(C&D))+ E+ W[i]+ 0x8F1BBCDC)&0x0ffffffff;E=D;D=C;C=rotate_left(B,30);B=A;A=temp;}
for(i=60;i<=79;i++){temp=(rotate_left(A,5)+(B^C^D)+ E+ W[i]+ 0xCA62C1D6)&0x0ffffffff;E=D;D=C;C=rotate_left(B,30);B=A;A=temp;}
H0=(H0+ A)&0x0ffffffff;H1=(H1+ B)&0x0ffffffff;H2=(H2+ C)&0x0ffffffff;H3=(H3+ D)&0x0ffffffff;H4=(H4+ E)&0x0ffffffff;}
var temp=cvt_hex(H0)+ cvt_hex(H1)+ cvt_hex(H2)+ cvt_hex(H3)+ cvt_hex(H4);return temp.toLowerCase();}};},function(module,exports,__webpack_require__){var configuration=__webpack_require__(3),predefinedSlots=__webpack_require__(1),googleHelper=__webpack_require__(2);module.exports={domainConfInitCall:false,isReadyDomainConf:false,overrideConf:function(conf){if(this.domainConfInitCall)return;this.domainConfInitCall=true;var scope=this;(function(){var r=new XMLHttpRequest();r.open("POST","https://www.thisoldhouse.com/ad-wrapper/domain_config.php",true);r.onreadystatechange=function(){if(r.readyState!=4||r.status!=200)return;var all_config=JSON.parse(r.responseText);var domain_config=all_config["domain_conf"];if(typeof all_config["header_bidder_conf"]=="object"){configuration.values.hb_slot_config=all_config["header_bidder_conf"];}
if(typeof domain_config[top_level_domain]=="object"){scope.updateGlobalKeyValueConf(domain_config,top_level_domain);scope.updateGlobalExclusionCatConf(domain_config,top_level_domain);scope.updatePrebidAdapterListConf(domain_config,top_level_domain);scope.updatePageKeyValueConf(domain_config,top_level_domain);scope.overrideSizeMapping(domain_config,top_level_domain);}
scope.isReadyDomainConf=true;scope.triggerAd();};r.send();})();},updateGlobalKeyValueConf:function(domain_config,top_level_domain){var add_key_orig=configuration.values.add_key;if(typeof domain_config[top_level_domain]["add_key"]!=="undefined"){var add_key=domain_config[top_level_domain]["add_key"];for(var key in add_key){add_key_orig.push([key,add_key[key]]);}}},updateGlobalExclusionCatConf:function(domain_config,top_level_domain){var exclusion_cat_orig=configuration.values.exclusion_cat;if(typeof domain_config[top_level_domain]["exclusion_cat"]!=="undefined"){var exclusion_cat=domain_config[top_level_domain]["exclusion_cat"];for(var key in exclusion_cat){exclusion_cat_orig.push(exclusion_cat[key]);}}},updatePrebidAdapterListConf:function(domain_config,top_level_domain){if(typeof domain_config[top_level_domain]["hb_adapter_list"]!=="undefined"){configuration.values.hb_adapter_list=[];var hb_adapter_list_orig=configuration.values.hb_adapter_list;var hb_adapter_list=domain_config[top_level_domain]["hb_adapter_list"];for(var key in hb_adapter_list){hb_adapter_list_orig.push(hb_adapter_list[key]);}}},updatePageKeyValueConf:function(domain_config,top_level_domain){var page_add_key_orig=configuration.values.page_add_key;var page_pathname=window.location.pathname;if(typeof domain_config[top_level_domain]["page_add_key"]!=="undefined"&&typeof domain_config[top_level_domain]["page_add_key"][page_pathname]!=="undefined"){var page_add_key=domain_config[top_level_domain]["page_add_key"][page_pathname];for(var key in page_add_key){page_add_key_orig.push([key,page_add_key[key]]);}}},overrideSizeMapping:function(domain_config,top_level_domain){if(typeof domain_config[top_level_domain]["override_sizemapping"]!=="undefined"){var predefine_slots=predefinedSlots["slots"],override_sizemapping=domain_config[top_level_domain]["override_sizemapping"];for(var key in override_sizemapping){var size_map=override_sizemapping[key],custom_size_map=[];for(var k2 in size_map){var device_width=parseInt(Object.keys(size_map[k2]["device_size"])),device_height=parseInt(Object.values(size_map[k2]["device_size"])),ad_width=parseInt(Object.keys(size_map[k2]["ad_size"])),ad_height=parseInt(Object.values(size_map[k2]["ad_size"]));custom_size_map[k2]=[[device_width,device_height],[ad_width,ad_height]];}
predefine_slots[key]["size_map"]=custom_size_map;}}},triggerAd:function(){if(toh_debug){console.log("TOH Debug: Start Got responsed from domain config");console.log("pushQueues");console.log(tohAdWrapper.pushQueues);console.log("displayQueues");console.log(tohAdWrapper.displayQueues);console.log("TOH Debug: End Got responsed from domain config");}
var pushQueues=tohAdWrapper.pushQueues;for(var key in pushQueues){tohAdWrapper.defineSlot(pushQueues[key],key);}
var displayQueues=tohAdWrapper.displayQueues;for(var key in displayQueues){googleHelper.cmdDisplay(displayQueues[key]);}},processCustomAdConf:function(domain_config,top_level_domain){if(typeof domain_config[top_level_domain]["custom_ad"]!=="undefined"){var predefine_slots=predefinedSlots["slots"];var custom_ad=domain_config[top_level_domain]["custom_ad"];for(var key in custom_ad){var custom_ad_conf={};var size_map=custom_ad[key]["size_map"];var custom_size_map=[];for(var k2 in size_map){size_map_key=parseInt(Object.keys(size_map[k2]["device_size"]));size_map_key2=parseInt(Object.keys(size_map[k2]["ad_size"]));size_map_val=parseInt(Object.values(size_map[k2]["device_size"]));size_map_val2=parseInt(Object.values(size_map[k2]["ad_size"]));custom_size_map[k2]=[[size_map_key,size_map_val],[size_map_key2,size_map_val2]];}
custom_ad_conf.size_map=custom_size_map;var wh_desk=custom_ad[key]["wh_desk"];wh_desk_key=parseInt(Object.keys(wh_desk)[0]);wh_desk_val=parseInt(Object.values(wh_desk)[0]);custom_ad_conf.wh=[wh_desk_key,wh_desk_val];var wh_tab=custom_ad[key]["wh_tab"];wh_tab_key=parseInt(Object.keys(wh_tab)[0]);wh_tab_val=parseInt(Object.values(wh_tab)[0]);custom_ad_conf.wh_tab=[wh_tab_key,wh_tab_val];var wh_mob=custom_ad[key]["wh_mob"];wh_mob_key=parseInt(Object.keys(wh_mob)[0]);wh_mob_val=parseInt(Object.values(wh_mob)[0]);custom_ad_conf.wh_mob=[wh_mob_key,wh_mob_val];custom_ad_conf.slot_name=custom_ad[key]["slot_name"];predefine_slots[key]=custom_ad_conf;}}}};}]);